### ISSUE TITLE
Parsing OData WebAPI Response.

### ISSUE THREAD

**Issue by BuairtRi** [devnixs/ODataAngularResources#1]
This is working with basic OData endpoints, but when you use the OData v4 endpoints, it's failing to recognize the response as a valid one.  It's expecting the response to be a simple array, but the ODataController sends back a more complex response type:

``` javascript
{
  "@odata.context":"http://local.testsite.com/odata/$metadata#TestData","value":[
    {
      "TestId":1,"Name":"test 1"
    },{
      "TestId":2,"Name":"test 2"
    },{
      "TestId":3,"Name":"test 3"
    },{
      "TestId":4,"Name":"test 4"
    },{
      "TestId":5,"Name":"test 5"
    }
  ]
}
```

Notice that this is an object, not an array. We need to unwrap the OData context wrapper, in order to get the "value" property which is what we want.

This is a relatively easy fix. On line 316 of the ODataResources.js file, we just need to add a simple if statement to detect the wrapper:

``` javascript
if (angular.isString(data['@odata.context'])) {
     data = data.value;
}
```

**Comment by devnixs** [comment]
Cool! Great Idea.
But we can even do better. We can take all the properties other than value and store them as properties of the array. So the array remains an arrays for compatibility purposes, but also have properties.
For example if the total count is provided :

``` javascript
{
  "@odata.context":"http://local.testsite.com/odata/$metadata#TestData",
   "value":[
    {
      "TestId":1,"Name":"test 1"
    },{
      "TestId":2,"Name":"test 2"
    }
  ],
"totalCount":10
}
```

we can do 

``` javascript
if (angular.isString(data['@odata.context'])) {
     var completeObject = data;
     data = data.value;
    for(var property in completeObject){
        if(property!=="value"){
              data["property"]=completeObject["property"]
        }
    }
}
```

And after that we could either do myUsers[0] or myUsers.totalCount

**Comment by NicoJuicy** [comment]
My response in my fiddler is this:

```
{
  "odata.metadata":"http://localhost:26696/odata/$metadata#Products","value":[
    {
    "Id":"505e1336-6e68-e511-beda-6c71d92133bc","title":"Tequila","sku":"000001","price":5.0,"isActive":true,"option1Id":null,"option1Values":null,"option2Id":null,"option2Values":null,"option3Id":null,"option3Values":null,"supplierId":null,"timeStamp":"AAAAAAAAB9E="
     }
   ]
}
```

So for some reason, this would be okay: 

angular.isString(data['odata.metadata']) instead of angular.isString(data['@odata.context'])

Currently have a modifier running after my bower. I'm using odata v4 from the nuget package. Previously 5.3.1, now 5.7.0.  

Still having the same issue.

Hold on, thought it was v4.0 as default. It's 3.0 as default. Need to download this for a correct scaffolder: https://visualstudiogallery.msdn.microsoft.com/db6b8857-06cc-4f40-95dd-a379f0494f45
