### ISSUE TITLE
Problem using Guid datatype in OData v4 query

### ISSUE THREAD

**Issue by ilyvion** [devnixs/ODataAngularResources#10]
I have this query:

```
Companies
    .filter("Id", new $odata.Value('3240569b-79f5-41b6-9a51-02fcc2aef24f', "Guid"))
    .query();
```

It results in this URL:
`[...]/odata/Sites?$filter=Id eq guid'3240569b-79f5-41b6-9a51-02fcc2aef24f'`

Which gives this error message:

```
{
  "error":{
    "code":"","message":"The query specified in the URI is not valid. Unrecognized 'Edm.String' literal 'guid'3240569b-79f5-41b6-9a51-02fcc2aef24f'' at '6' in 'Id eq guid'3240569b-79f5-41b6-9a51-02fcc2aef24f''."
  }
}
```

If I remove the "guid" prefix and the quotes around the GUID, everything works fine. This is in accordance with the OData v4 spec: https://www.oasis-open.org/committees/download.php/50849/odata-v4.0-wd04-part2-url-conventions-2013-09-27.docx (see section 5.1.1.6.1). I have specified `isodatav4: true` to `$odataresource`.

**Comment by ilyvion** [comment]
I fixed it for me by changing this code bit:

```
if(this.type.toLowerCase() === "guid"){
    return "guid'"+this.value+"'";
```

to

```
if(this.type.toLowerCase() === "guid"){
    return this.value;
```

Although that will probably break functionality with previous OData versions, and shouldn't be considered a generic fix.

**Comment by NicoJuicy** [comment]
Are you sure it's 4.0? Did you check the response header of odata ( which includes the version)

**Comment by devnixs** [comment]
Thanks for the tip. I'm using ODatav4 and I'm requried to use the **guid'...'** syntax.
So I won't change the library to use that format.

**Comment by NicoJuicy** [comment]
He is right though: http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part2-url-conventions/odata-v4.0-errata02-os-part2-url-conventions-complete.html#_Toc406398153

I'm also facing the same issue when using it in a $filter. According to the specs, guid seems to be used as a integer which is correct ( logic wise). The library doesn't work when using an odata v4 $filter.

Double checked it right now.

**Comment by NicoJuicy** [comment]
Theirs a partial fix in my fork https://github.com/NicoJuicy/ODataAngularResources/commit/9f1f195582cbdd9d365b3517bd273ca5c5e40868

Updated the specs and code.
Now tested it out in practise and pushed it.

**Comment by ilyvion** [comment]
So what you're telling me is that because whatever server-side OData implementation you're testing against does OData v4 wrong, you won't do it right?

**Comment by devnixs** [comment]
I acknowledged my mistake and accepted a pull requests that fixes it already : https://github.com/devnixs/ODataAngularResources/pull/17
You can **bower update** to get the latest version with the fix.

**Comment by ilyvion** [comment]
Pardon me, all I saw was your comment where it said that you won't change the library to use that format. Thanks, sorry for being misinformed.

**Comment by NicoJuicy** [comment]
@devnixs thanks for immediatly putting it into bower :)
