### ISSUE TITLE
library does not parse correctly a result set.

### ISSUE THREAD

**Issue by ionescuvictor** [devnixs/ODataAngularResources#11]
i have the following json from a query that returns a list:

{
"odata.metadata": "http://localhost:63447/odata/$metadata#CompanyViewModels",
"value":[
{
"Id": 1,
"CompanyName": "Company1"
},
{
"Id": 2,
"CompanyName": "Company2"
}
]
}

it is not an array, because it has the 'odata.metadata' json payload.

and it throws an error here.

if (angular.isArray(data) !== (!isSingleElement && !!action.isArray) && !forceSingleElement) {
                                      throw $resourceMinErr('badcfg',
                                        'Error in resource configuration for action `{0}`. Expected response to ' +
                                        'contain an {1} but got an {2} (Request: {3} {4})', name, (!isSingleElement && action.isArray) ? 'array' : 'object',
                                        angular.isArray(data) ? 'array' : 'object', httpConfig.method, httpConfig.url);
                                  }

why? because the object is not an array ( [] ).

i had to add the following.

 if (data.value)
                                  {
                                      data = data.value;
                                  }

asp.net web api for backend.

should have if property named odata.metadata exists then something.

**Comment by jmarbutt** [comment]
I agree on this, I am having the same issue. I would like to see it just check for data.value to validate it in case it isn't a "true" odata end point

**Comment by jmarbutt** [comment]
@ionescuvictor where are you doing the data.value check?

**Comment by ionescuvictor** [comment]
sorry for late reply.

check for 

// Need to convert action.isArray to boolean in case it is undefined
                                  // jshint -W018

right after that you would write

if(data.value)
{
data = data.value
}

The resource is expecting an array.If not it will throw an error.

the asp.net odata web api response is like this

{ 
  metadata.endpoint : 'http://someurl/resourcename/metadata',
  value: [ { id: 3, name: john },{ id: 5, name: Alex },{ id: 9, name: Alfred }]
}

obviously that is not an array object from the body.However 'Value" is.

**Comment by NicoJuicy** [comment]
Update to odata version v4, you are using v4 and the wrong odata scaffolder. See https://github.com/devnixs/ODataAngularResources/issues/1#issuecomment-144823254

Made the same mistake :) - odata v4 starts with @odata.context= as response, while v3 responds with odata.metadata as response. Then the check in this library fails.

For more information check: https://github.com/devnixs/ODataAngularResources/issues/1, solution on the bottom ( upgrade to v4)

Topic may close or you can suggest a solution for odata v3 ( but that is outdated)
