### ISSUE TITLE
Well written library.  Question on ability to separate functionality.

### ISSUE THREAD

**Issue by McShauno** [devnixs/ODataAngularResources#112]
This is a great library and I appreciate the author's ability to write clean, decent and efficient code.

Is it possible for me somehow separate out the query building aspect of this library?  For example, I have an Odata resource that I am calling using $http and would like to easily format out the the part of the URI for querying Odata.  However, I don't need the $resource aspect of the library as I already have multiple angular services using the $http directly.  I'd like to be able to pass in to my service something like an ODataQuery object that just appends the necessary URI structure for the query (i.e. '?$expand=Owner').

Thank you.

**Comment by devnixs** [comment]
Hi McShauno,

It's pretty simple, use $odataProvider and then execute() it to get the query.

````javascript
function($odataProvider){
    var odata = new $odataProvider();
    var query = odata.filter("name","bob").execute();
}
````

I didn't test that code so you might need to change it.

**Comment by McShauno** [comment]
Perfect, thank you!
