### ISSUE TITLE
Patch/Merge

### ISSUE THREAD

**Issue by NicoJuicy** [devnixs/ODataAngularResources#12]
I haven't seen support for patch/merge.

Do you have plans to support this? I'll probably help you write it ( but in a later phase of my current project). 

It's enabled by default in odata web api scaffolder.

I use this in a current project of mine and the author helped the team of odata / webapi: https://github.com/Starcounter-Jack/JSON-Patch

**Comment by devnixs** [comment]
Hi, Patch and Merge are not supported yet and I don't plan to add the feature any time soon.
You are welcome to write it and submit a pull request.

**Comment by NicoJuicy** [comment]
Thanks for the response!
