### ISSUE TITLE
Problem when OData returns V3 "odata.metadata" property rather than V4 "@odata.context"

### ISSUE THREAD

**Issue by victorsoliveira** [devnixs/ODataAngularResources#16]
Hi, i have an local OData V3 API that returns a result like it.

```
{
odata.metadata: "http://localhost/odata/v1/$metadata#Customers",
value: [ ]
}
```

When i try to use a comnand like "odata().query()" the lib throws an error like it.

```
Error in resource configuration for action 'odata'. Expected response to contain an array but got an object. ...
```

Looking the code, i found a validation in line 926 that no consider another property, just "@odata.context". 

You have any reason for that?
The lib just support OData V4?

**Comment by victorsoliveira** [comment]
A possible solution would be change the code below... (founded at line 926)

``` javascript
if (data && angular.isString(data['@odata.context']) && data.value) {
  var fullObject = data;
  data = data.value;
  for (var property in fullObject) {
    if (property !== "value") {
      value[property] = fullObject[property];
    }
  }
}
```

... to anything like that ...

``` javascript
if (data && (angular.isString(data['@odata.context']) || angular.isString(data['odata.metadata'])) && data.value) {
  var fullObject = data;
  data = data.value;
  for (var property in fullObject) {
    if (property !== "value") {
      value[property] = fullObject[property];
    }
  }
}
```

.. that works for me.

**Comment by victorsoliveira** [comment]
Any restriction about this possible change ?

**Comment by devnixs** [comment]
This has been solved here : https://github.com/devnixs/ODataAngularResources/issues/5

**Comment by victorsoliveira** [comment]
Thanks @devnixs , i didn't saw this issue, my bad! ;)
