### ISSUE TITLE
Function calls returning empty

### ISSUE THREAD

**Issue by nnarasimha** [devnixs/ODataAngularResources#18]
I am unable to use function calls, returns me nothing. 

$scope.products = $odataresource("http://ccc.net/Ingredients")
                            .odata()
                            .filter(new $odata.Func("startswith","Material_Group",mat_gp),true)
                            .query();

Can one of you help me out?

**Comment by devnixs** [comment]
First, I can't access http://www.ccc.net/Ingredients
Then be careful about cross domain requests : https://en.wikipedia.org/wiki/Same-origin_policy
You have to setup a Access-Control-Allow-Origin header on the remote host.

**Comment by nnarasimha** [comment]
Thanks for the response, I got it resolved. Does $update to only post or patch as well? Can you please provide with a simple example?

**Comment by devnixs** [comment]
I can't give you an example but $update does a PUT.
