### ISSUE TITLE
Support system query option $count

### ISSUE THREAD

**Issue by Cleudi** [devnixs/ODataAngularResources#19]
As described here:
http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part2-url-conventions/odata-v4.0-errata02-os-part2-url-conventions-complete.html#_Toc406398166

Results in a URL like http://anyurl.com/Entities/&$count=true

**Comment by devnixs** [comment]
This has already been taken care of here : https://github.com/devnixs/ODataAngularResources/pull/4 and here : https://github.com/devnixs/ODataAngularResources/pull/3
