### ISSUE TITLE
Support more advanced filters

### ISSUE THREAD

**Issue by ilyvion** [devnixs/ODataAngularResources#21]
In OData, this is a valid $filter query: `/odata/Foo?$filter=Bars/all(b: b/Baz ne 0)` -- it will give you the `Foo` entities where all the `Bars`' `Baz` property is not equal to 0. I'm in need of making this type of query, and I'm struggling to get ODataAngularResources to produce one.

Closest I got was this: `.filter("Bars/all(b: b/Baz", "!=", "0)")`, but it (obviously) thinks that "0)" is a string, and produces this output: `Bars/all(b: b/Baz ne '0)'`.

Any help on how to get this to work would be appreciated.

**Comment by devnixs** [comment]
It's ugly but you can trick the library to not add "" around the second parameter by explicitly specifying the type to be a boolean.
See demo here: http://jsfiddle.net/8mwk0tmm/

**Comment by ilyvion** [comment]
Thanks, that's a nice workaround, but it doesn't really solve the issue I reported, does it? You didn't really say whether you intend to support these filters properly or not. Since you closed it, I'm leaning towards not, but correct me if I'm wrong.

(And when I say "support", I obviously mean in some sensible built-in-to-the-library way.)

**Comment by devnixs** [comment]
Why doesn't it solve your issue?
I think this feature is necessary and I will develop it sooner or later, but I can't give you an ETA.
And If someone develops it, I would be happy to accept a pull request.

**Comment by ilyvion** [comment]
Mostly I'm surprised that you close the issue until it's been implemented. I mean, it's your project, so you do as you please, but issues are typically not closed right away. The issue was named "Support more advanced filters", which aren't yet supported. Do you get where I'm coming from?

**Comment by subpx** [comment]
Would be nice if you contributed to the project instead wasting people's time with pointless comments.

**Comment by ilyvion** [comment]
I guess in your world, reporting missing features is not contributing? Not everybody has your supernatural coding skills and infinite free time, you know.

**Comment by devnixs** [comment]
The way I see it issues should stay open until the problem is resolved. But there is no bug or problem here it's just about a new feature that doesn't exist yet.
