### ISSUE TITLE
Suggestion for implementing access_token header?

### ISSUE THREAD

**Issue by dhiraj** [devnixs/ODataAngularResources#22]
I'm using ODataAngularResources against an OAuth2 protected service. For this, I need to pass an Authorization Bearer header with the access token set in it.

I am able to do this for GET based requests like query, etc. by sending it into odata.headers of the 3rd parameter of the `$odataresource()` constructor, but this doesn't seem to work for sending `$save()` based POST requests.

Thoughts, suggestions, ideas on the best strategy to implement this would be much appreciated!

**Comment by devnixs** [comment]
If you could submit a jsfiddle that reproduces the error, that would be great!
Thanks

**Comment by dhiraj** [comment]
I got it working with an $http interceptor. Closing this, thanks.

**Comment by figuerres** [comment]
it would be nice if you told us what you did, I am just now learning angular so your post now tells me I have to learn more but a sample would help.

**Comment by dhiraj** [comment]
I don't have the code with me at the moment, did it on-site for a client but the basic gist is this, you write a  new $http interceptor and add new headers centrally. You make a service that manages and stores authentication related information. Depending on authenticated or not you add access_token or other headers directly into every $http request. 

All requests through angularjs flow through $http generally so it's the perfect place to write it in.

**Comment by nafnaf1000** [comment]
Use this, and it will deal with all the interceptor and authentication issues.

http://bitoftech.net/2014/06/01/token-based-authentication-asp-net-web-api-2-owin-asp-net-identity/
