### ISSUE TITLE
How can update the entity if the primary key is GUID

### ISSUE THREAD

**Issue by iamrommel** [devnixs/ODataAngularResources#23]
I'm still using the version 3 of OData and the result was of my debugging was shown on this

![odatadelete](https://cloud.githubusercontent.com/assets/177265/11086235/00e6d8e6-888a-11e5-9685-b814eb2b67ae.png)

https://www.dropbox.com/s/k9z6ujqiogc7tst/OdataDelete.png?dl=0

**Comment by devnixs** [comment]
I'm sorry, this library doesn't support ODatav3
