### ISSUE TITLE
deeplevel orderBy

### ISSUE THREAD

**Issue by NicoJuicy** [devnixs/ODataAngularResources#25]
Is there a way to order by a child property?

Eg. ( possible syntax)

```
.orderBy("Trajects.Priority").query()
```

Or isn't this supported in Odata? I can't seem to find it in the docs. They suggest navigating to the child and then ordering: http://notify-arrival.sapico.me/odata/Routes(9cbaab82-1245-4015-a106-66c440a751fa)/Trajects?$orderby=Order%20asc

Is it possible to order it on a higher level? If you haven't came accross this yet or have no idea.. Just close this issue and i'll check the method described above :)

(If it's possible i would add it in ODataAngularResources if it doesn't exist yet, that's why i'm asking)

**Comment by NicoJuicy** [comment]
I did it in javascript instead of an odata query. I don't think $orderby for children of arrays works :) It's simple enough and does the job.

```
//in a loop based on http://www.w3schools.com/jsref/jsref_sort.asp
response[i].Trajects.sort(function (a, b) {
    return a.Priority- b.Priority;
})
```

**Comment by nafnaf1000** [comment]
ODataAngularResources is an Amazing tool, 

Thank you

I was wondering this also, 

I wanted to do some advanced expand and select's

would look something like this...

http://services.odata.org/V4/Northwind/Northwind.svc/Orders?$select=OrderID&$expand=Order_Details($select=UnitPrice;$orderby=Quantity)

except in my case I go 4 levels down... not just 2

thank you for you reply.
