### ISSUE TITLE
How to write a PATCH request?

### ISSUE THREAD

**Issue by dhiraj** [devnixs/ODataAngularResources#27]
I'm in the need of writing a HTTP PATCH request to my OData API. I've got an array of `Order` items, and I need to be able to add, edit, remove Items in the `Order`, without submitting the whole order back to the API, only what's changed.

Please suggest / document how to accomplish this. I've tried to use both $update and $save, but am facing problems, either the server ends up trying to / creating a duplicate `Order` or nothing gets saved.

**Comment by devnixs** [comment]
Hi dhiraj,
PATCH requests are not supported by this library.
I think the easiest way would be to do it manually and use $http.

**Comment by dhiraj** [comment]
Alright, thanks.
