### ISSUE TITLE
Odata V4 and parameters

### ISSUE THREAD

**Issue by figuerres** [devnixs/ODataAngularResources#33]
I am trying to get the library to take a parameter but it looks like it only works for older odata not for V4.

what I was trying is like this:
$odataresource("OData/users(:id)", { id: '@id' } , {}, { odatakey: 'id', isodatav4: true }).odata().query();

if I use some versions with /:id  I can get the id value but for V4 it needs the "( )" format.
I am new with this so if I am making a mistake please explain it.

I can get a url that has /users/2  or one that has /users()   but not /users(2)  unless i do it without the parameter and just make the string.

is the a bug in the library or that the Odata 4 support is not finished yet?
if it's a thing that I can fix where should I look in the source to fix it?

thanks!

**Comment by devnixs** [comment]
Hi figuerres,
Don't add the (:id) yourself, the library will do it for you:
https://github.com/devnixs/ODataAngularResources#updating-entries-with-odata-v4

Then use the get() method, not the query() to retrieve a single element when you know the id.

https://github.com/devnixs/ODataAngularResources#retrieving-a-single-element
