### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by Ross-Rawlins** [devnixs/ODataAngularResources#34]
I am trying to do a get but it keeps going through as options how do I fix this?

Request Method:OPTIONS
Status Code:405 Method Not Allowed

**Comment by devnixs** [comment]
Can you provide the code that does that?

**Comment by Ross-Rawlins** [comment]
Thanks we where able to determine it was a server sided bug.

On 18 February 2016 at 17:07, Raphael ATALLAH notifications@github.com
wrote:

> Can you provide the code that does that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/devnixs/ODataAngularResources/issues/34#issuecomment-185760336
> .

## 

Ross Rawlins
_Tel:_ 021 531 7087
_Cell:_ 072 424 9480
_Skype:_ ross.rawlins
_Email:_ ross@duovili.co.za

http://www.duovili.co.za
https://plus.google.com/113781084234234096576/posts
https://www.facebook.com/Duovili
http://www.linkedin.com/company/duovili/     https://twitter.com/Duovili

This e-mail message and all attachments contain the CONFIDENTIAL AND
PROPRIETARY information of DUOVILI DEVELOPMENTS. and may contain LEGALLY
PRIVILEGED information. If you are not the intended recipient, you are
hereby notified that any disclosure, distribution, or use of this e-mail,
its attachments or any information contained therein is unauthorised and
prohibited. If you have received this in error, please contact the sender
immediately and delete this e-mail and any attachments.
