### ISSUE TITLE
Lambda Operator Support

### ISSUE THREAD

**Issue by yyean** [devnixs/ODataAngularResources#38]
Is there any plans to support Lambda operations?

http://www.odata.org/getting-started/basic-tutorial/#lambda

**Comment by devnixs** [comment]
I think that it's a very important feature and this library lacks it.
But I'm not planning in developing it anytime soon.
Pull requests are welcome though.

If you really need to use the lambda operations a workaround would be to use the transformUrl method.
https://github.com/devnixs/ODataAngularResources#transform-the-final-query-url
