### ISSUE TITLE
odata search

### ISSUE THREAD

**Issue by Ross-Rawlins** [devnixs/ODataAngularResources#39]
How do you implement odata search function.

**Comment by devnixs** [comment]
Can you be more specific?

**Comment by Ross-Rawlins** [comment]
I was trying to run the odata search function but then I realized that odata search function (www.test.com/run('searchText')) will only search against the primary key assigned to it. So if I want to run a multi column search I would have to create a custom odata search function which means I wouldnt be using the basic one.

But if I wanted to implement the search function how would I implement it?

**Comment by devnixs** [comment]
I'm not sure I understand what you mean by search function. When I need to search across multiple fields, I usually create a query similar to that : 
contains(column1,"value") or contains(column2, "value") or ...
you can build that using the predicates to build the or statements and the function calls
