### ISSUE TITLE
getUrl?

### ISSUE THREAD

**Issue by vance** [devnixs/ODataAngularResources#42]
Love this library, I'm using it to help make a dynamic query builder. 

I'm wondering if there's a way to simply get the built-out URL? Something like this, but less verbose. I did not see a typeScript definition that would do this. It would be handy to display to the user the query they are generating with the UI. If not, I could maybe make PR based on the transformUrl function. 

Here's how I'm wrapping it currently

```
   getUrl(filter):string => {
    var theUrl ='';
    this.buildOdataResource([filter]).transformUrl(function(url){
      console.log('this.buildOdataResource >> ', url );
      theUrl = url;
      return url;
    });
   return theUrl;
}
```

this is what I see as available functions:

```

class Provider<T> {
    private callback;
    private filters;
    private sortOrders;
    private takeAmount;
    private skipAmount;
    private expandables;
    constructor(callback: ProviderCallback<T>);
    filter(operand1: any, operand2?: any, operand3?: any): Provider<T>;
    orderBy(arg1: string, arg2?: string): Provider<T>;
    transformUrl(transformMethod : (url:string)=>string): Provider<T>;
    take(amount: number): Provider<T>;
    skip(amount: number): Provider<T>;
    private execute();
    query(success?: ((p:T[])=>void), error?: (()=>void)): T[];
    single(success?: ((p:T)=>void), error?: (()=>void)): T;
    get(key: any, success?: ((p:T)=>void), error?: (()=>void)): T;
    expand(...params: string[]): Provider<T>;
    expand(params: string[]): Provider<T>;
    select(...params: string[]): Provider<T>;
    select(params: string[]): Provider<T>;
    count(success?: (result: ICountResult) => any, error?: () => any):ICountResult;
    withInlineCount(): Provider<T>;
  }
```

**Comment by Rogerio-Soares** [comment]
You can at least get/transform the generated url during query, maybe you can find something arround :
`
var myResource= $odataresource('/odata/blabbla', {}, {}, {
    odatakey: 'myEntity',
    isodatav4: true
});

var odata = myResource.odata()
    .withInlineCount()
    .skip(xxx)
    .take(xxx);

odata .transformUrl(function (url) {
    //Do stuff with url
    return url;
}).query(function (o) {
    console.log('Yea, ODataAngularResources rocks!')
}, function () {
    console.log('Oops, something wrong happened!')
})
`

Regards,

**Comment by vance** [comment]
It seems like transformUrl has a problem. When I call it on a valid resource, I never hit the breakpoint in the callback function. My resource is valid, as I can actually perform a query and get a result from oData endpoint.

My resource: 
`{filters: Array[1], sortOrders: Array[0], takeAmount: 100, skipAmount: 0, expandables: Array[0]…}`

Result:

```
theResource.transformUrl(function(url){
      // never gets called
      console.log('the url >> ', url );
      theUrl = url;
      return url;
    });

//program continues...

```

**Comment by devnixs** [comment]
Weird, do you think you could reproduce the issue on a jsfiddle?
You can use that one if you want to fork it. 
http://jsfiddle.net/h22f7596/

About the typescript definition, there is no method other than transformUrl to do that. 
If you want to build it, you can go ahead and submit a pull request.

Thanks!

**Comment by Zegoat** [comment]
Using .execute() seems to do the job :

```
$scope.myOdataUrl = 
        $odataresource("http://services.odata.org/V4/Northwind/Northwind.svc/Products")
        .odata()
        .filter('UnitPrice','>',10)
        .filter('Discontinued',true)
        .orderBy('UnitsInStock','asc')
        .expand('Category')
        .execute();
```

**Comment by vance** [comment]
Ah cool, I'm not exactly sure, but I did another query and can get the string from transformUrl. Thanks for bearing with me, I'm writing an abstract wrapper that dynamically generates query based on user input, so my raw implementation is a bit too complex to show everything here.
