### ISSUE TITLE
DateTime formatting

### ISSUE THREAD

**Issue by vance** [devnixs/ODataAngularResources#43]
I'm not sure how to format ISO dates. If I put a raw date in the filter value, it appends single quote (%27) to the string, and odata says it is invalid. additionally, if I specify `datetime'Tue Mar 15 2016 14:41:17 GMT-0700 (PDT)'` It adds string literal around that, too. Putting in an actual js Date object also causes it to parse the value as a string.

I would expect to just provide a date object and have it serialize it into odata query param. Is there another way?

If so, maybe just add that example in the readme

**Comment by vance** [comment]
Ah! I see from the spec:

```

            it('should work with dates with odatav4 and specified type', function() {
                var value = new $odata.Value(new Date("06/02/2015 10:23"),'datetime');
                expect(value.execute(true)).toMatch(/^2015-06-02T.+Z$/);
            });
```

I shall try this.

**Comment by vance** [comment]
Sorry, I'm at a loss here. I tried everything to supply the datetime type to filter. It always hits the `executeWithUndefinedType` I'm digging through the source and the specs and still can't figure it out.

```
theResource.filter( filter.property.name, filter.operator.operator, filterValue );
```

if i try `filterValue = { value: myDate, type:'datetime' }` I get an error that [object object] is not allowed. I also tried various ways of doing odatajs.Value( myDate, 'datetime') etc. but I'm not sure how to do this.

thanks for the help!

**Comment by devnixs** [comment]
Hi Vance,
Can you make sure that the argument that you passed is a JS Date object?
Can you also try to run the test by opening the file _SpecRunner.html ?
If all the tests are passing, then I you could to set breakpoints in the methods you want to debug and then comparing why it works in the tests and not in your project

**Comment by vance** [comment]
yes, I am performing `angular.isDate(filterValue)` before supplying to the filter....

Wait! I overlooked the obvious, I had not configured to odata v4! Duh! Sorry to have bothered you! It is a lot to keep track of, writing a generic implementation around ODataAngularResources while still also being relatively new to odata itself.

```
   var url = this.utils.path.combine(Settings.apiServer, 'odata', service.name );
    var odataResource:OData.IResourceClass<any> = this.odataResource(url, {}, {}, {
      isodatav4: true
    });
```
