### ISSUE TITLE
Support for bound / unbound functions & actions?

### ISSUE THREAD

**Issue by bondarewicz** [devnixs/ODataAngularResources#45]
This is a question rather than an issue... 

Does **ODataAngularResources** supports [functions](http://docs.oasis-open.org/odata/odata-json-format/v4.0/errata02/os/odata-json-format-v4.0-errata02-os-complete.html#_Toc403940649) & [actions](http://docs.oasis-open.org/odata/odata-json-format/v4.0/errata02/os/odata-json-format-v4.0-errata02-os-complete.html#_Toc403940650)?

**Comment by vance** [comment]
Is this what you mean? like contains() etc. From the docs:

```
var users = User.odata()
.filter(new $odata.Func("endswith","FullName","Doe"), true)
.query();
```

**Comment by bondarewicz** [comment]
based on this [postman collection](http://www.odata.org/getting-started/learning-odata-on-postman/) it looks like you can call predefined actions on odata endpoints, I would like to know how can I perform following using **ODataAngularResources**:

```
POST http://services.odata.org/V4/TripPinService/People('russellwhyte')/Microsoft.OData.SampleService.Models.TripPin.ShareTrip
```

with `application/json` payload

``` json
{
"userName": "scottketchum",
"tripId": 0
}
```

or how to invoke `POST, DELETE or PATCH` requests

**Comment by vance** [comment]
+1 

Hm. I'm not a contributor, but this is something I may need down the road. I've taken a pretty deep dive down this library now. This may be easier at this point to do with normal angular $resource or $http. I just tried several things to accomplish calling the bound function. My litmus for success is getting the same response as the Postman example. So far, I have been unable to formulate this request using angular-odata-resources. But, maybe there's a way...

using **vanilla** $http:

```
this.http({      url:"http://services.odata.org/V4/TripPinService/People('russellwhyte')/Microsoft.OData.SampleService.Models.TripPin.ShareTrip",
      method:'POST',
      data:{
        userName: "scottketchum",
        tripId: 0
      }
    }).then((result)=>{
    });

//response is 200 OK, just like postman
```

**Comment by devnixs** [comment]
This is what I do when I need bound functions : 

``` javascript
this.Assets = $odataresource('/odata/Assets', { assetId: '@assetId' },
{                       
    'deleteThumbnail':  { method: 'GET', url: '/odata/Assets(:assetId)/Default.DeleteThumbnail()' },
    'refreshThumbnail': { method: 'GET', url: '/odata/Assets(:assetId)/Default.RefreshThumbnail()' },
 }, { odatakey: 'assetId', isodatav4: true })
```
