### ISSUE TITLE
Angular material integration

### ISSUE THREAD

**Issue by Ross-Rawlins** [devnixs/ODataAngularResources#49]
I am trying to integrate this to run with angular material select.

http://codepen.io/pen/?editors=1010

That link shows how to implement the async to show. I am told to use a promise and that will run it but I cant get it to run. Currently I am using the code below.

```
fObject.get = function (queryObject)
            {
                $rootScope.loading = true;
                rsrcObject.query(queryObject,
                        function (data)
                        {
                            $rootScope.loading = false;
                            fObject.list = data;
                        },
                        function (data)
                        {
                            $rootScope.loading = false;
                            baseSrvc.returnError(data);
                        });
            };
```

**Comment by devnixs** [comment]
Your codepen is empty and I have no idea how your issue is related to this library

**Comment by NicoJuicy** [comment]
Although your question is bad and unrelated. You should probably return rsrcObject.query() as that is the promise. You are using the promise instead of returning it.

**Comment by Ross-Rawlins** [comment]
I resolved this some time ago so we can close this.
