### ISSUE TITLE
Complex route key replacements does not work

### ISSUE THREAD

**Issue by Rykie** [devnixs/ODataAngularResources#50]
In the simple case where you have a simple route like: 
`$odataresource('/user/:userId', {userId:'@id'});`
the expected result is `"/user(5)"` and that is OK, but for more complex routes where the Id is NOT at the end of the route, it does not work.

For example:
`$odataresource('/user/:userId/details', {userId:'@id'});`
The expected result is: `"/user(5)/details"` however the actual result is `"user/details(5)"`

**Comment by devnixs** [comment]
Sorry but that library doesn't support complex queries like these. You're welcome to submit a pull request that would support that though.

**Comment by kyse** [comment]
That seems more like rest syntax than odata.  How is your database setup between user and detail?
