### ISSUE TITLE
Non-nested or statements

### ISSUE THREAD

**Issue by benjamin-wilson** [devnixs/ODataAngularResources#51]
I have a long list of or statements because odata does not support a "field in (list)" syntax. Code looks something like:

`$odata.Predicate.or([predicate0...predicateN]);`

**Expected:** _(ID eq 0) or (ID eq 1) or (ID eq 2) or (ID eq 3)_
**Actual:** _(((ID eq 0) or (ID eq 1)) or (ID eq 2)) or (ID eq 3)_

I have so many fields that the server errors because the or statements are nested too deep.

**Comment by devnixs** [comment]
You can easily configure that maximum.
If you are using ASP.Net ==> https://msdn.microsoft.com/en-us/library/system.web.http.odata.enablequeryattribute.maxnodecount%28v=vs.118%29.aspx#P:System.Web.Http.OData.EnableQueryAttribute.MaxNodeCount

**Comment by benjamin-wilson** [comment]
I think this is still an issue, the above being a workaround. I don't think one would expect these statements to be formatted like they are.

**Comment by kyse** [comment]
I do agree, I opted not to use the built in predicate functionality because of this unexpected nesting.

Maybe I'll have some time this one day to look at an acceptable modification for denixs.

In the mean time you can do the following in your code.

```
var request = resource.odata().select('...').expand('...');
var predicates = [];
// I check my metadata for proper syntax, you can do what ever you wish here...
var md = $myresourceofmetadata.getTable('tablename');
filter.columns.forEach(function (column) {
    if (column.isRowHeader)
        return;
    var mdCol = md.getColumn(column.field);
    if (mdCol)
        switch(mdCol.type) {
            case 'Edm.String':
                predicates.push('contains(' + column.field.replace('.','/') + ",'" + filter.value + "')");
                break;
            case 'Edm.Int32':
                if (Number.parse(filter.value) !== NaN)
                    predicates.push(column.field.replace('.', '/') + " eq " + filter.value);
                break;
            case 'Edm.Boolean':
                if (filter.value === 'true' || filter.value === 'false')
                    predicates.push(column.field.replace('.', '/') + " eq cast('" + filter.value + "'," + mdCol.type + ')');
                break;
            default:
                break;
        }

});

var combined = '$filter=' + predicates.join(' or ') + '&';

// Manually inject your predicates
request.transformUrl(function(qry) {
    return combined + qry;
}

// And proceed as usual
request.query();
```
