### ISSUE TITLE
Complex expressions in lambda operation not working

### ISSUE THREAD

**Issue by subpx** [devnixs/ODataAngularResources#57]
Tried to use the latest update on my own project and realised that it doest work for what I actually needed it for. Current solution only supports single simple expressions.

I have made an update that seems to work much better. I will do some more testing and then update tests and documentation.

**Comment by devnixs** [comment]
Sounds good! Thanks!

**Comment by subpx** [comment]
Sorry been flat out. I will submit a pull request soon

**Comment by devnixs** [comment]
Awesome, thanks!
