### ISSUE TITLE
still confused please help

### ISSUE THREAD

**Issue by figuerres** [devnixs/ODataAngularResources#59]
we have a query that works but is not really good on the server.
the server queries al whole table and then picks a record right now due to how this is written. I want to have it work better but I can't seem to get the right way to do it.

what goes to fiddler now is like this:  /aspnetusers/aspnetusers?$filter=Id%20eq%201157&$expand=AspNetRoles
what I want to have it do is like this: /aspnetusers/aspnetusers(1157)?$expand=AspNetRoles

the client side right now is using this
    return $odataresource(url + "/atrakapi/aspnetusers/aspnetusers").odata()
               .filter("Id", id)
               .expand("AspNetRoles")
               .query();

so how do I change that from filter to a get by id 
trying different things so far gets me errors but not the right data.
sorry I am so dense on this, I am more of a C# developer not a JS developer

**Comment by kyse** [comment]
If you're doing a get for a single record, there's no need to apply the filter on the id.  Also, the query() method on the odata provider is used for retrieving an expected array of data, you want to use get(id) for retrieving a single entity.

You'll want to let the provider know your key however if you ever plan on doing patch/put/deletes though.

So let's change up that call to the following:

```
var id = 1157;

// 3 ways to create the service
// Non odata v4
var service1 = $odataresource(url + "/atrakapi/aspnetusers/aspnetusers/:id", {id: "@Id"})
// odata v4
var service2 = $odataresource(url + "/atrakapi/aspnetusers/aspnetusers", "Id");
// odata v4 explicitly defined
var service3 = $odataresource(url + "/atrakapi/aspnetusers/aspnetusers", {}, {}, { isodatav4: true, odatakey: 'Id' });

return service.odata().expand("AspNetRoles").get(id);
```

**Comment by figuerres** [comment]
thanks!   I think one of the things that is confusing is that some samples are for the old way before V4 and others are for V4 but they often do not call that out.
also I had not found a clear example of how to pass the id  and the different forms of how they declared the key ....   I think your example will get me sorted out now!!!

**Comment by kyse** [comment]
Agreed it's kind of messy.  I believe a result of trying to support the stock Resource syntax so as not to break existing projects converting to this library.
