### ISSUE TITLE
Issue in MethodCall -> any lambda function

### ISSUE THREAD

**Issue by java2kus** [devnixs/ODataAngularResources#62]
Hi,

We are trying to use the following code to generate the URL filter which looks like the below:

`
$filter=orgAssociations/any(o:o/orgJobs/any(oj:oj/departmentCode eq 'f1'))
`
When we call the filter, the generated URL is 

`
$filter=orgAssociations/any(o:o/rgJobs/any(o:o/(departmentCode eq 'f1'))
`

Please see the above URL where the letter o from orgJobs is omitted.   Also, the  bracket in the end is missing in the generated URL.

Code snippet below:

```
presourceClass.odata().filter(new $odata.Func('any','orgAssociations',
                            new $odata.Func('any',
                                new $odata.Property('orgJobs'),
                                new $odata.Predicate('departmentCode',
                                'f1')
                                )
                            ));

          //$filter=orgAssociations/any(o:o/rgJobs/any(o:o/(departmentCode eq 'f1'))
          console.log(provider.execute() + ' -> url');

```

I traced the issue to the following line:

https://github.com/devnixs/ODataAngularResources/blob/master/src/odatamethodcall.js#L43

i.e. change
`invocation += expression.substring(1, expression.length-1);`
to
`invocation += expression;
`
If we comment out the above line, then everything is getting generated as expected.   

Another issue is with the line below:

https://github.com/devnixs/ODataAngularResources/blob/master/src/odatamethodcall.js#L39

Since both orgAssociations and orgJobs has the same first character 'o', the variable name is the same which results in an error.   Hence the strategy of using the first character for variable name is not working.   

Please advise.

**Comment by subpx** [comment]
@java2kus Refactored the lambda functions and never got around to doing a pull request.
Just tested it with your desired url and this would be the result:

$filter=orgAssociations/any(o:o/orgJobs/any(d:(d/departmentCode%20eq%20%27f1%27)))

I will submit a pull request. Documentation will be updated with new method for using Lambda operators

**Comment by java2kus** [comment]
@subpx  Thanks a lot for submitting the pull request.   I tested the code and it works perfectly fine.   Please note that this will result in a regression in existing codebase where the assumption is that the var prefix will be added automatically for simple variables which uses eq clause.   After reviewing the pull request, I think the way you have implemented is the correct way and it will handle all types of complex queries.

**Comment by devnixs** [comment]
Just merged https://github.com/devnixs/ODataAngularResources/pull/63
