### ISSUE TITLE
OData 2.0 result set

### ISSUE THREAD

**Issue by IvoMoor** [devnixs/ODataAngularResources#67]
Data returned from OData 2.0 is structured like:
{ d : { results : [{ ... }, { ... }] } }

As the ODataAngularResources expects an array, the following error message is thrown:
_Expected response to contain an array but got an object_

Changing code below is solving this issue for me:

```
var promise = $http(httpConfig).then(function(response) {
                var data = response.data,
                  promise = value.$promise;
```

To

```
var promise = $http(httpConfig).then(function(response) {
                var data = response.data.d.results,
                  promise = value.$promise;
```

**Comment by kyse** [comment]
Odd output.  But no problems.

Please see angular's documentation for [$resource](https://docs.angularjs.org/api/ngResource/service/$resource).

Specifically in the actions section there are two options available to assist you here.

You could probably overload the odata action and set this to false if you want automatic handling.

> isArray – {boolean=} – If true then the returned object for this action is an array, see returns section.

Or preferably you could take over transforming the response yourself.

> transformResponse – {function(data, headersGetter)|Array.<function(data, headersGetter)>} – transform function or an array of such functions. The transform function takes the http response body and headers and returns its transformed (typically deserialized) version. By default, transformResponse will contain one function that checks if the response looks like a JSON string and deserializes it using angular.fromJson. To prevent this behavior, set transformResponse to an empty array: transformResponse: []

```
var resource = $odataresource('/user/:userId',{userId:'@id'},{
  query: {
    transformResponse: function (response) {
      return angular.fromJson(response.data.d.results);
    }
  }
}, {});

var response = resource.odata().query(function(response) {
  console.info('Received Response.' response);
});
```

**Comment by IvoMoor** [comment]
Thanks again for your help. Great angular module! Changing the code to the following solved the issue:

```
const resource = this.$odataresource(
        this.SERVICE.URL,
        {},
        {
          odata: {
            transformResponse: function (response) {
              return angular.fromJson(response).d.results;
            },
            isArray: false
          }
        },
        {}
      )

resource
        .odata()
        .select([
          this.SERVICE.COLUMNS.COL01,
          this.SERVICE.COLUMNS.COL02
        ])
        .format('json')
        .query(
          (data) => {
            deferred.resolve(data);
          },
          (error) => {
            deferred.reject(error);
          }
        );
```
