### ISSUE TITLE
OData 2.0 $type parameter

### ISSUE THREAD

**Issue by IvoMoor** [devnixs/ODataAngularResources#68]
In OData 2.0 it is possible to retrieve data in either JSON or XML format by specifying the $format parameter. It would be nice to have this parameter available via the module as well.

Right now as a workaround I use:

```
.transformUrl(function(url){
        return url+'&$format=json';
      })
```

**Comment by kyse** [comment]
`resource.odata().format('json').query();` will return what you desire.

Guess we need to get that in the documentation.

**Comment by IvoMoor** [comment]
Thanks! This indeed solves the issue!
