### ISSUE TITLE
Can you patch an entity?

### ISSUE THREAD

**Issue by Martin-Andersen** [devnixs/ODataAngularResources#69]
Hi I building an odata v4 api and I want to if it possible to patch an entity with ODAR

**Comment by devnixs** [comment]
Hi, no this is not supported yet.

**Comment by kyse** [comment]
I'm assuming by ODAR you mean odataresources library.

This is what I do for patch.

```
var User = $odataresource('/user',{},{
  odata: {
    isArray: true,
  },
  patch: {
    method: 'PATCH',
  }, {
    isodatav4: true,
    odatakey: 'Id',
    persistence: true,
  });

var bob = new User();
bob.Id = 5;
bob.MiddleInitial = 'K';
bob.$patch();
```

Now the different story is when you use `User.odata().query()` to retrieve a model to patch.  Obviously it will have everything you optionally selected/expanded in the query on the model, so doing a patch on that populated response resource object will just patch the entire model back.  There's no watchers on which properties have changed in the model to only serialize those properties.

**Comment by devnixs** [comment]
I guess you could 

``` javascript
delete bob.id
```

and all other properties that you don't want to send.

**Comment by kyse** [comment]
Don't delete the key.  The API needs to know which entity to patch.  But
yes, they could just delete the other properties.  Lots of pointless work.
If I'm patching, I am building out a model of whats changed.  If I need to
track whats changed on the model, I suppose I could apply watchers
manually, seems like a lot of work when u can just do a post back with the
full entity.
