### ISSUE TITLE
Remove Angular 1 requirement?

### ISSUE THREAD

**Issue by techniq** [devnixs/ODataAngularResources#71]
Currently this is the best javascript OData library I've found and have been very happy with it's capabilities, so much so I'd love to use it on non-Angular 1 projects (server side, Angular 2, React, etc).

Have you considered removing the Angular 1 dependencies (angular.module, $http, etc)?

I know it would be a big undertaking, and I've considered forking and going down this path myself (as it should be a different package name) but didn't know if you had it on your roadmap.

**Comment by devnixs** [comment]
Hi techniq,
No this is not planned but I agree, it would be awesome to have the same library, but with no dependencies.

**Comment by techniq** [comment]
@devnixs thanks for the quick reply.  When time allows, I might take a stab at this, although I just did a quick search and found a few other odata libraries that might be worth investigating (when I'm not using Angular 1)
- https://github.com/bodia-uz/odata-filter-builder
- https://github.com/gallayl/angular2-odata
- https://github.com/janhommes/o.js

**Comment by devnixs** [comment]
Also, you might want to take a look at http://www.getbreezenow.com/breezejs

**Comment by techniq** [comment]
Thanks. I had a few months back but it didn't look to support v4, which
we're using.
