### ISSUE TITLE
using `orderBy`on `expandPredicate`

### ISSUE THREAD

**Issue by ahmed-sherien** [devnixs/ODataAngularResources#72]
is there a way to use `orderBy` on expanded properties to produce a request like that:

```
http://localhost:4744/odata/Forms(2012034d-14e4-492e-a883-88997b49748d)?$expand=Actions($orderby=Order),Zones($orderby=Order;$expand=ControlGroups($orderby=Order;$expand=Controls($orderby=Order)))
```

**Comment by kyse** [comment]
I don't think I've ever been able to get orderBy to work properly within an expand.  Wouldn't it be orderBy=Actions/Order,Zones/Order?

**Comment by ahmed-sherien** [comment]
it's OData v4 I've tried it and it is working ...

**Comment by kyse** [comment]
Should be able to add it as an option then.  I'll see if I have time this week.

**Comment by ahmed-sherien** [comment]
great ... thanks

**Comment by ahmed-sherien** [comment]
thanks for your effort @kyse
