### ISSUE TITLE
Best practise for building dynamic filters

### ISSUE THREAD

**Issue by bondarewicz** [devnixs/ODataAngularResources#76]
Imagine user needs to be able to filter the dataset on any matching properties
how one would go about passing user selection to multiple chained .filter() functions ?

Example: 
We have 2 select boxes, first for UnitPrice & second for Discounted property.

User tries to filter all products which are Discontinued

```
vm.products = $odataresource("http://services.odata.org/V4/Northwind/Northwind.svc/Products")
.odata()
.filter('Discontinued',true)
.query();
```

now user would like to add new filter to see all with UnitPrice > 10

```
vm.products = $odataresource("http://services.odata.org/V4/Northwind/Northwind.svc/Products")
.odata()
.filter('Discontinued',true)
.filter('UnitPrice','>',10)
.query();
```

How do you guys handle dynamic changes to filters and additions / removals of filters ?  Predicates?

**Comment by devnixs** [comment]
Simply create a query object

``` javascript
var query = $odataresource("http://services.odata.org/V4/Northwind/Northwind.svc/Products")
.odata()

if(something){
query = query.filter(...);
}

if(somethingElse){
query = query.filter(...);
}

results = query.query();
```
