### ISSUE TITLE
There is no way to put up transforms on get, query methods

### ISSUE THREAD

**Issue by parv0888** [devnixs/ODataAngularResources#78]

**Comment by NicoJuicy** [comment]
Do you mean this?

https://github.com/devnixs/ODataAngularResources#transform-the-final-query-url

**Comment by parv0888** [comment]
No , I dont mean to transform the final query Url. I want to transform the response that im getting back. Something that is done normally by using transformRequest and transformResponse in angular js resource. As shown on this page
https://docs.angularjs.org/api/ngResource/service/$resource

**Comment by NicoJuicy** [comment]
Transformrequest and TransformResponse seems like a promise feature to me ( not sure)    

```
odata().filter(something).query().$promise
//https://docs.angularjs.org/api/ng/service/$http
```

Can you do something with that?

**Comment by kyse** [comment]
For the odata action, you'll probably need to pass the query method a success param to handle the transform.  Might be a cool idea to add a transformResponse to the options param object of the resource init to affect the odata action.

**Comment by parv0888** [comment]
just checked out the source code. Should work if we pass in requestTransform and/or responseTransform with the odata action in while instantiating the resource.

```
new $odataresource('name', 'url', {
    odata : {
        isArray : true, 
        method : 'GET', 
        requestTransform : [fn1, fn2,...],
        responseTransform : [fn1, fn2,...]}
})
```

All the properties i pass in here are directly copied to the underlying httpConfig and finally passed into $http service
