### ISSUE TITLE
Selecting in expanded queries

### ISSUE THREAD

**Issue by ilyvion** [devnixs/ODataAngularResources#8]
I was happy to see that you have support for this OData v4 syntax:

> var result = User.odata().expand("roles", "role").query();
> //  /user?$expand=roles($expand=role)

But what I want to make use of (and what I can't seem to figure out how to do with this library) is the following v4 syntax:

> /user?$expand=roles($select=id)

Which would expand the **user** object with its **roles**, but only include the **roles**' id property.

So far I've tried these without any success:

> [...].select(['roles.id'])
> [...].select(['roles/id'])
> [...].select([['roles', 'id']])
> [...].select([{ 'roles': ['id'] }])

This works, but it feels kind of "wrong", especially from a fluent API perspective:

> [...].expand("roles($select=id)")

At that point I'm gaining very little from the API, as I'm basically building the query myself.

**Comment by devnixs** [comment]
I'm sorry it's doesn't support selecting fields of an expanded model.
The only way to do it is the way you did it and I agree it feels wrong.
Maybe I will add it in a next release.
