### ISSUE TITLE
groupby & aggregate

### ISSUE THREAD

**Issue by bondarewicz** [devnixs/ODataAngularResources#81]
Trying to get groupby & aggregate functions to work... 
can they can specified as `new $odata.Func()` ? 
Url I'm trying to get is `$apply=groupby((Status), aggregate(Id with countdistinct as Total))`

**Comment by devnixs** [comment]
I'm sorry @bondarewicz, aggregate functions are not support by this library.
If you really want to do it with this library, you can do it the dirty way, with the tranformUrl() method.

**Comment by bondarewicz** [comment]
@devnixs thanks for reply, I thought that might be the case.
