### ISSUE TITLE
Fuctions And Actions

### ISSUE THREAD

**Issue by hbdbim** [devnixs/ODataAngularResources#82]
I not found how to invoke functions or actions.
[Odata v4 Function documentation](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Toc453752310)
[Odata v4 Action documentation](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Toc453752311)

**Comment by devnixs** [comment]
Hi hbdbim.
Here's how you do it : https://github.com/devnixs/ODataAngularResources#function-calls

**Comment by hbdbim** [comment]
Not that kind of function ( endswith).

like that
'/api/EntitySet/SomeAction(Param1=value1,Param2=value2)'

**Comment by devnixs** [comment]
That's how I do it : 

``` javascript
this.Avatars = $odataresource('/odata/Avatars', { avatarId: '@avatarId' },
    {   
         'select': { method: 'GET', url: '/odata/Avatars(:avatarId)/Default.Select()' },
    }, { odatakey: 'avatarId', isodatav4: true });
```
