### ISSUE TITLE
edit http headers

### ISSUE THREAD

**Issue by fvenezia** [devnixs/ODataAngularResources#85]
Like angular`$resource`, can you add http header access?
It will help to set custom attributes in it.

Thanks

**Comment by devnixs** [comment]
Yes, you can use $odataresource just like a normal $resource object.

**Comment by fvenezia** [comment]
OK I get it!
For the record, the resource must declare actions explicitely.
For example :
`var myRes = $odataresource('url', {}, {
          odata: {
              method: 'GET',
              isArray: true,
              headers: {
                  'customAtt' : 'myCustomValue'
              }
          }
      }, { odatakey: 'Id', isodatav4: true });`

Perhaps, you can write it in documentation?

Thanks, very good work :)
