### ISSUE TITLE
Sending Post Data

### ISSUE THREAD

**Issue by Chris3773** [devnixs/ODataAngularResources#87]
Is there a way to send the data from $save or other post methods that send the data in the body and not the URI?

**Comment by kyse** [comment]
Can you provide an example of what you're doing, its results, and what you're looking for.

**Comment by Chris3773** [comment]
I'm trying to use actions from the OData v4 spec.

Controller:

```
[HttpPost]
public async Task<IHttpActionResult> Rate([FromODataUri] int key, ODataActionParameters parameters)
{
    if (!ModelState.IsValid)
    {
        return BadRequest();
    }

    int rating = (int)parameters["Rating"];
    db.Ratings.Add(new ProductRating
    {
        ProductID = key,
        Rating = rating
    });

    try
    {
        await db.SaveChangesAsync();
    }
    catch (DbUpdateException e)
    {
        if (!ProductExists(key))
        {
            return NotFound();
        }
        else
        {
            throw;
        }
    }

    return StatusCode(HttpStatusCode.NoContent);
}
```

OData Call:
`http://localhost/Products(1)/ProductService.Rate`

Post data sent:

```
POST http://localhost/Products(1)/ProductService.Rate HTTP/1.1
Content-Type: application/json
Content-Length: 12

{"Rating":5}
```

**Comment by kyse** [comment]
Ok, so I assume you already have an odataresource created for retrieving and saving your products.  It really depends on how you're managing the rating.

Either you are using a new odataresource instance call to ProductRatings and filter on ProductID.  Or from your example, I'd imagine you're able to grab the product rating by doing an expand on the Ratings navigation property under the Product entity which would return a list of ProductRating's where the ProductID = Product.ID.

First off, POST generally means adding a new entity.  I'd suggest changing your API to accept PUT and PATCH.  @devnixs correct me if I'm wrong, I'm not aware of a way to get the post method to generate a url of Products(1).  My API accepts navigation property entities from PATCH, and will handle adding new entities if needed.

If you're good with using PUT or PATCH methods, there are two options you can take.  I've written out some tests you can use as examples to see the two options you have.  I'll post the tests to the repo soon along with an update I've just completed if you need to seem them in action.

```
        describe('Method call options', function() {
            it('should work with custom urls', function () {
                var successInterceptor = jasmine.createSpy('sucessInterceptor');
                var ProductRating = $odataresource('/Products(:productId)/ProductService.Rate', { productId: "@ProductID" }, { update: { method: 'PUT', interceptor: { response: successInterceptor } } });
                $httpBackend.expectPUT("/Products(5)/ProductService.Rate")
                    .respond(204, undefined, undefined, 'No Content');
                var productRating = new ProductRating();
                productRating.ProductID = 5;
                productRating.Rating = 10;
                var response = productRating.$update();
                $httpBackend.flush();
                console.log(successInterceptor.calls.mostRecent());
                expect(successInterceptor).toHaveBeenCalled();
                expect(successInterceptor.calls.mostRecent().args[0].status).toBe(204);
                expect(successInterceptor.calls.mostRecent().args[0].statusText).toBe('No Content');
            });
            it('should work with custom actions', function () {
                var successInterceptor = jasmine.createSpy('sucessInterceptor');
                var Products = $odataresource('/Products', {}, {
                    rate: {
                        method: 'PUT',
                        url: '/Products(:productId)/ProductService.Rate',
                        params: {
                            productId: '@ProductID',
                        },
                        interceptor: {
                            response: successInterceptor
                        },
                    },
                }, { odatakey: 'ProductID' });
                $httpBackend.expectGET('/Products(5)')
                    .respond(200, { ProductID: 5, Rating: 9 });
                var product = Products.odata().get(5);
                $httpBackend.flush();
                expect(product.ProductID).toBe(5);
                expect(product.Rating).toBe(9);
                $httpBackend.expectPUT("/Products(5)/ProductService.Rate")
                    .respond(204, undefined, undefined, 'No Content');
                product.Rating = 10;
                product.$rate();
                $httpBackend.flush();
                expect(successInterceptor).toHaveBeenCalled();
                expect(successInterceptor.calls.mostRecent().args[0].status).toBe(204);
                expect(successInterceptor.calls.mostRecent().args[0].statusText).toBe('No Content');
            });
        });
```

Option 1: Create a new odataresource object setup to that endpoint.  new it to get your model, update the model with keys and values.   Call $update, on it.
Option 2: add a rate action to your odataresource targeting your products api.  Provide the desired method, a custom url, and required params to it.  Obviously this test case is based on the Rating property being on the Products entity model.  You'll most likely have a navigation property containing Ratings.  And you will be updating that array on your model.  So you'll want to add a request interceptor to transform the data from the Products entity, to the desired Rating entity you want to add.
Option 3: I'd say option 1 is probably the easiest, and safer.  You could always add a successCallback to the Products odata().query() call to append a ProductRatings array Resource object to the final Products Resource object, use Object.defineProperty to make it !enumerable so it doesn't affect serialization for updates for that Resource.  Then you can use the $update method from that array Resource object when you need to add new entities.  In that update callback, have it add the new Rating to it's array.

Frankly, DB functions and SP's exposed through OData suck and don't merge together if you ask me.  Would probably be cleaner to extend your API's patch method to accept navigation properties and add or update entities where appropriate based on the keys provided.
