### ISSUE TITLE
Can i use with RestAngular

### ISSUE THREAD

**Issue by fofiedelly** [devnixs/ODataAngularResources#9]
Hi and thanks for this useful library. 
I'm trying to integrate Odata to my AngularJS project and i initialiy use the Restangular, your library use instead $resource to make it's own Resource. Is it then possible to use this library without the use of the  $odataService ??

**Comment by devnixs** [comment]
Hi,
I don't know what Restangular and $odataService si but this library is not meant to be used with anything other than plain angular.
