### ISSUE TITLE
delete a resource without getting it

### ISSUE THREAD

**Issue by doubret** [devnixs/ODataAngularResources#96]
Hi,
Can i delete a resource without getting it first ?
For exemple, if i do this it works, but i am reading the resource before deleting it :

                    var resource = this.Resource.odata().get(id);
                    resource.$promise.then(result => result.$delete() ......

It would be nice if i could simply delete it from the id.

Thanks

**Comment by Zegoat** [comment]
I may be wrong, but I think you could do something like below:
```
var myUser = new this.Resource();
myUser.myId = id;
myUser.$delete();
```

**Comment by kyse** [comment]
Technically, an angular resource exists to act as an adapter between the API and some kind of data module like a grid or form.  Not really as a generalized API client.  So the resource would more than likely already be populated on the resource object before you call a method which requires a key be on the resource.  Hopefully Rogerio's solution is an easy work around for you.  Don't forget to initialize the resource with the proper key field(s) your API expects.

**Comment by devnixs** [comment]
Thanks @kyse for your answer.
A shorter version of Rogerio's code is : 
```javascript
var myUser = new this.Resource({myId : id});
myUser.$delete();
```

**Comment by doubret** [comment]
Thank you all.
